### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by FIFARenderZ** [PSPReverse/PSPTool#18]
So this happens when you're trying to run PSPTool on a TRX40/EPYC Rome bios.

The complete traceback:

> Traceback (most recent call last):
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\Scripts\psptool-script.py", line 11, in <module>
    load_entry_point('psptool==2.1', 'console_scripts', 'psptool')()
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\__main__.py", line 79, in main
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\psptool.py", line 30, in from_file
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\psptool.py", line 38, in __init__
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\blob.py", line 50, in __init__
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\blob.py", line 97, in _find_entry_table
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\fet.py", line 44, in __init__
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\fet.py", line 90, in _parse_entry_table
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\fet.py", line 71, in _create_dir
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\directory.py", line 67, in __init__
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\directory.py", line 145, in _parse_entries
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\entry.py", line 154, in from_fields
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\entry.py", line 177, in __init__
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\entry.py", line 334, in _parse
  File "C:\Users\Sebastiaan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psptool-2.1-py3.7.egg\psptool\entry.py", line 405, in _parse_hdr
OverflowError: cannot fit 'int' into an index-sized integer

Any idea on why this might be happening?

**Comment by FIFARenderZ** [comment]
I kind of fixed it by installing it via pip. I suspect it must've been a broken install, but it did work on the A320 bios.

**Comment by RobertBuhren** [comment]
The current head has some issues, I'll try to resolve these in the next days.
