### ISSUE TITLE
error parsing T14 Gen 1 firmware

### ISSUE THREAD

**Issue by orangecms** [PSPReverse/PSPTool#28]
I tried to read an image for/from a Lenovo T14 Gen 1 (the AMD variant ;)).

This is what I get when trying to parse the image from an actual device:
```
Warning: Couldn't find corresponding key in blob for entry at: 0x4ff00. Type: SMU_OFFCHIP_FW~0x8
Warning: Couldn't find corresponding key in blob for entry at: 0x70e00. Type: SMU_OFF_CHIP_FW_2~0x12
Warning: Couldn't find corresponding key in blob for entry at: 0x81000. Type: SEC_GASKET~0x24
Warning: Couldn't find corresponding key in blob for entry at: 0x83f00. Type: ABL0~0x30
Warning: Couldn't parse pubkey entry 0x9
Warning: ERROR id is not a pubkey
Warning: Couldn't find corresponding key in blob for entry at: 0x154000. Type: PSP_FW_TRUSTED_OS~0x2
Warning: Couldn't find corresponding key in blob for entry at: 0x167400. Type: SMU_OFFCHIP_FW~0x8
Warning: Couldn't parse pubkey entry 0x9
Traceback (most recent call last):
  File "/usr/bin/psptool", line 33, in <module>
    sys.exit(load_entry_point('psptool==2.2', 'console_scripts', 'psptool')())
  File "/usr/lib/python3.9/site-packages/psptool/__main__.py", line 80, in main
    psp = PSPTool.from_file(args.file, verbose=args.verbose)
  File "/usr/lib/python3.9/site-packages/psptool/psptool.py", line 31, in from_file
    pt = PSPTool(rom_bytes, verbose=verbose)
  File "/usr/lib/python3.9/site-packages/psptool/psptool.py", line 39, in __init__
    self.blob = Blob(rom_bytes, len(rom_bytes), self)
  File "/usr/lib/python3.9/site-packages/psptool/blob.py", line 48, in __init__
    self._find_entry_table()
  File "/usr/lib/python3.9/site-packages/psptool/blob.py", line 86, in _find_entry_table
    self.fets.append(Fet(self, fet_offset, self.agesa_version))
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 45, in __init__
    self._parse_entry_table()
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 89, in _parse_entry_table
    self._create_dir(addr, dir_magic)
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 72, in _create_dir
    self.directories.append(Directory(self, dir.secondary_directory_address, 'secondary', self.blob))
  File "/usr/lib/python3.9/site-packages/psptool/directory.py", line 69, in __init__
    self._parse_entries()
  File "/usr/lib/python3.9/site-packages/psptool/directory.py", line 150, in _parse_entries
    if entry == existing_entry:
  File "/usr/lib/python3.9/site-packages/psptool/entry.py", line 277, in __eq__
    return self.type == other.type and self.get_address() == other.get_address() and \
AttributeError: 'NoneType' object has no attribute 'type'
```

From an update image (https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14-type-20ud-20ue/downloads/driver-list/component?name=BIOS%2FUEFI):

```
$ psptool --json code\$GetExtractPath\$/R1BET58W/\$0AR1B00.FL1               498ms  Sat 12 Dec 2020 03:01:23 AM UTC
Warning: Couldn't find corresponding key in blob for entry at: 0x50220. Type: SMU_OFFCHIP_FW~0x8
Warning: Couldn't find corresponding key in blob for entry at: 0x71620. Type: SMU_OFF_CHIP_FW_2~0x12
Warning: Couldn't find corresponding key in blob for entry at: 0x81320. Type: SEC_GASKET~0x24
Warning: Couldn't find corresponding key in blob for entry at: 0x84220. Type: ABL0~0x30
Warning: Couldn't parse pubkey entry 0x9
Warning: ERROR id is not a pubkey
Warning: Couldn't find corresponding key in blob for entry at: 0x154420. Type: PSP_FW_TRUSTED_OS~0x2
Warning: Couldn't find corresponding key in blob for entry at: 0x168820. Type: SMU_OFFCHIP_FW~0x8
Warning: Couldn't parse pubkey entry 0x9
Traceback (most recent call last):
  File "/usr/bin/psptool", line 33, in <module>
    sys.exit(load_entry_point('psptool==2.2', 'console_scripts', 'psptool')())
  File "/usr/lib/python3.9/site-packages/psptool/__main__.py", line 80, in main
    psp = PSPTool.from_file(args.file, verbose=args.verbose)
  File "/usr/lib/python3.9/site-packages/psptool/psptool.py", line 31, in from_file
    pt = PSPTool(rom_bytes, verbose=verbose)
  File "/usr/lib/python3.9/site-packages/psptool/psptool.py", line 39, in __init__
    self.blob = Blob(rom_bytes, len(rom_bytes), self)
  File "/usr/lib/python3.9/site-packages/psptool/blob.py", line 48, in __init__
    self._find_entry_table()
  File "/usr/lib/python3.9/site-packages/psptool/blob.py", line 86, in _find_entry_table
    self.fets.append(Fet(self, fet_offset, self.agesa_version))
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 45, in __init__
    self._parse_entry_table()
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 89, in _parse_entry_table
    self._create_dir(addr, dir_magic)
  File "/usr/lib/python3.9/site-packages/psptool/fet.py", line 72, in _create_dir
    self.directories.append(Directory(self, dir.secondary_directory_address, 'secondary', self.blob))
  File "/usr/lib/python3.9/site-packages/psptool/directory.py", line 69, in __init__
    self._parse_entries()
  File "/usr/lib/python3.9/site-packages/psptool/directory.py", line 150, in _parse_entries
    if entry == existing_entry:
  File "/usr/lib/python3.9/site-packages/psptool/entry.py", line 277, in __eq__
    return self.type == other.type and self.get_address() == other.get_address() and \
AttributeError: 'NoneType' object has no attribute 'type'
```

You can extract the update image using `innoextract`.

**Comment by cwerling** [comment]
Hi @orangecms! If this is still a blocker for you, would you mind sharing the innoextracted file with me? Cheers!

**Comment by orangecms** [comment]
I am not sure about distribution rights from Lenovo's side. However, you can download the file `r1buj60w.exe` following the link above, then under "BIOS Update (Utility & Bootable CD) for Windows 10 (64-bit) - ThinkPad T14 Gen 1 (Types 20UD, 20UE), P14s Gen 1 (Types 20Y1, 20Y2)", select "VIEW ALL FILES(4)", and choose "BIOS Update Utility".
This is the direct link: https://download.lenovo.com/pccbbs/mobiles/r1buj60w.exe
Then just run `innoextract r1buj60w.exe` (best in a new directory) and finally `psptool --json code\$GetExtractPath\$/R1BET58W/\$0AR1B00.FL1`.

I am not really blocked by it, just playing around with several firmware images in order to find useful ways to visualize and work with them. So I ran into this case here and wanted to report back, hoping it's valuable to you. :)

**Comment by lokeb** [comment]
I am having the same problem. Here's the ROM.
[rom.zip](https://github.com/PSPReverse/PSPTool/files/6837778/rom.zip)

**Comment by lokeb** [comment]
@cwerling Have you been able to look into this? Also have you had any success in examining the blob itself?

**Comment by orangecms** [comment]
@lokeb Maxbe this is interesting for you:
[Fiano's utk](https://github.com/linuxboot/fiano) will be extended to support PSP data structures. They have been defined in https://github.com/9elements/converged-security-suite and are being ported over. I'll add that to [utk-web](https://github.com/orangecms/utk-web), so you'll be able to load an image into your web browser and get a visualization.

For a preview, see https://github.com/orangecms/utk-web/tree/wasm (will be pushed over to `main` when done).

**Comment by itewqq** [comment]
Having the same problem on T14

**Comment by cwerling** [comment]
> 

Please check out the latest version of PSPTool (2.4). I am able to parse the ROM now just fine.

```
Warning: Unknown FET entry with magic bytearray(b'2BHD') at ROM address 0x73000
Warning: Unknown FET entry with magic bytearray(b'\x02\x00\x00\x83') at ROM address 0x0
Warning: Unknown FET entry with magic bytearray(b'0H\xfd\xf7') at ROM address 0x5500
+-----+----------+-----------+----------+---------------+
| ROM |   Addr   |    Size   |   FET    |     AGESA     |
+-----+----------+-----------+----------+---------------+
|  0  | 0x17d050 | 0x1000000 | 0x19d050 | AGESA_UNKNOWN |
+-----+----------+-----------+----------+---------------+
+--+-----------+----------+------+-------+---------------------+
|  | Directory |   Addr   | Type | Magic | Secondary Directory |
+--+-----------+----------+------+-------+---------------------+
|  |     0     | 0x1f1050 | PSP  |  $PSP |       0x294000      |
+--+-----------+----------+------+-------+---------------------+
+--+---+-------+----------+---------+---------------------------------+----------+-----------+---------------------------+
|  |   | Entry |  Address |    Size |                            Type | Magic/ID |   Version |                      Info |
+--+---+-------+----------+---------+---------------------------------+----------+-----------+---------------------------+
|  |   |     0 | 0x1f1450 |   0x440 |              AMD_PUBLIC_KEY~0x0 |     144E |         1 |                           |
|  |   |     1 | 0x411450 | 0x10740 |          PSP_FW_BOOT_LOADER~0x1 |     $PS1 | 0.11.2.5F | verified(144E), sha256_ok |
|  |   |     2 | 0x1f1950 |  0xe5c0 | PSP_FW_RECOVERY_BOOT_LOADER~0x3 |     $PS1 | 0.11.2.5F | verified(144E), sha256_ok |
|  |   |     3 | 0x1fff50 | 0x20c00 |              SMU_OFFCHIP_FW~0x8 |     $PS1 | 0.37.4B.0 |     compressed, sha256_ok |
|  |   |     4 | 0x17d051 |     0x0 |          SOFT_FUSE_CHAIN_01~0xb |          |           |                           |
|  |   |     5 | 0x220b50 |  0xf690 |          SMU_OFF_CHIP_FW_2~0x12 |     $PS1 | 0.37.4B.0 |     compressed, sha256_ok |
|  |   |     6 | 0x230250 |    0x10 |               WRAPPED_IKEK~0x21 |          |           |                           |
|  |   |     7 | 0x231050 |  0x1000 |               TOKEN_UNLOCK~0x22 |          |           |                           |
|  |   |     8 | 0x232050 |  0x2f00 |                 SEC_GASKET~0x24 |     $PS1 |  B.9.0.78 |            verified(BCC5) |
|  |   |     9 | 0x234f50 |  0x19f0 |                            0x45 |     $PS1 |  B.9.1.78 |            verified(BCC5) |
|  |   |    10 | 0x236950 |   0x290 |                       ABL0~0x30 |          |   0.0.0.0 | verified(CF65), sha256_ok |
|  |   |    11 | 0x2a3b50 |  0x5fc0 |                            0x3c |     $PS1 | 11.A.0.16 |            verified(2FCA) |
|  |   |    12 | 0x2a9b50 |  0x1900 |               KEY_DATABASE~0x50 |     $PS1 |         1 | verified(144E), sha256_ok |
|  |   |    13 | 0x411050 |   0x400 |   !PL2_SECONDARY_DIRECTORY~0x40 |          |           |                           |
+--+---+-------+----------+---------+---------------------------------+----------+-----------+---------------------------+


+--+-----------+----------+-----------+-------+---------------------+
|  | Directory |   Addr   |    Type   | Magic | Secondary Directory |
+--+-----------+----------+-----------+-------+---------------------+
|  |     1     | 0x411050 | secondary |  $PL2 |          --         |
+--+-----------+----------+-----------+-------+---------------------+
+--+---+-------+----------+---------+-----------------------------+----------+------------+---------------------------+
|  |   | Entry |  Address |    Size |                        Type | Magic/ID |    Version |                      Info |
+--+---+-------+----------+---------+-----------------------------+----------+------------+---------------------------+
|  |   |     0 | 0x411450 | 0x10740 |      PSP_FW_BOOT_LOADER~0x1 |     $PS1 |  0.11.2.5F | verified(144E), sha256_ok |
|  |   |     1 | 0x421c50 |   0x440 |          AMD_PUBLIC_KEY~0x0 |     144E |          1 |                           |
|  |   |     2 | 0x422150 | 0x14350 |       PSP_FW_TRUSTED_OS~0x2 |     $PS1 |  0.11.2.5F | verified(D945), sha256_ok |
|  |   |     3 | 0x1ce050 | 0x20000 |             PSP_NV_DATA~0x4 |          |            |                           |
|  |   |     4 | 0x436550 | 0x20c00 |          SMU_OFFCHIP_FW~0x8 |     $PS1 |  0.37.4B.0 |     compressed, sha256_ok |
|  |   |     5 | 0x457150 |   0x440 |      SEC_DBG_PUBLIC_KEY~0x9 |     0475 |          1 |            verified(144E) |
|  |   |     6 | 0x17d051 |     0x0 |      SOFT_FUSE_CHAIN_01~0xb |          |            |                           |
|  |   |     7 | 0x457650 | 0x1f100 | PSP_BOOT_TIME_TRUSTLETS~0xc |     $PS1 |   3.2F.0.5 | verified(CC7D), sha256_ok |
|  |   |     8 | 0x476750 |  0xf690 |      SMU_OFF_CHIP_FW_2~0x12 |     $PS1 |  0.37.4B.0 |     compressed, sha256_ok |
|  |   |     9 | 0x485e50 |  0x2040 |           DEBUG_UNLOCK~0x13 |     $PS1 |  0.11.2.5F | verified(11F8), sha256_ok |
|  |   |    10 | 0x487f50 |   0x664 |                        0x20 |          |    0.0.0.0 |            verified(76AC) |
|  |   |    11 | 0x488650 |    0x10 |           WRAPPED_IKEK~0x21 |          |            |                           |
|  |   |    12 | 0x489050 |  0x1000 |           TOKEN_UNLOCK~0x22 |          |            |                           |
|  |   |    13 | 0x48a050 |  0x2f00 |             SEC_GASKET~0x24 |     $PS1 |   B.9.0.78 |            verified(BCC5) |
|  |   |    14 | 0x48cf50 | 0x2a83b |                 MP2_FW~0x25 |          |    4.0.5.8 |            verified(7C83) |
|  |   |    15 | 0x4b7850 | 0x1b770 |         DRIVER_ENTRIES~0x28 |     $PS1 |  0.11.2.5F | verified(D945), sha256_ok |
|  |   |    16 | 0x4d3050 |  0x3100 |            S0I3_DRIVER~0x2d |     $PS1 | 8.17.30.30 | verified(CC7D), sha256_ok |
|  |   |    17 | 0x4d6150 |   0x290 |                   ABL0~0x30 |          |    0.0.0.0 | verified(CF65), sha256_ok |
|  |   |    18 | 0x543350 |  0x5fc0 |                        0x3c |     $PS1 |  11.A.0.16 |            verified(2FCA) |
|  |   |    19 | 0x549350 |  0x19f0 |                        0x45 |     $PS1 |   B.9.1.78 |            verified(BCC5) |
|  |   |    20 | 0x54ad50 |   0x210 |             FW_INVALID~0x44 |     $PS1 |    0.0.0.0 |            verified(462E) |
|  |   |    21 | 0x551450 |  0x1900 |           KEY_DATABASE~0x50 |     $PS1 |          1 | verified(144E), sha256_ok |
|  |   |    22 | 0x552d50 |  0x1070 |                        0x51 |     $PS1 |          1 | verified(144E), sha256_ok |
|  |   |    23 | 0x553e50 |  0x5b70 |                        0x58 |     $PS1 |    0.0.0.0 |            verified(EBDF) |
|  |   |    24 | 0x559a50 |   0x220 |                        0x59 |     $PS1 |    0.0.0.0 |            verified(EBDF) |
|  |   |    25 | 0x559d50 |  0x5100 |                        0x47 |     $PS1 |  4.11.0.1B |            verified(61CE) |
|  |   |    26 | 0x867050 | 0x40000 |                        0x54 |          |            |                           |
+--+---+-------+----------+---------+-----------------------------+----------+------------+---------------------------+
```
