### ISSUE TITLE
python 3.9 :: 'Blob' object has no attribute 'dual_rom'

### ISSUE THREAD

**Issue by adriansev** [PSPReverse/PSPTool#29]
Hi! while trying to look into a cap file for ASUS PRIME B550-PLUS i got this:
```
psptool PRIME-B550-PLUS-ASUS-1216.CAP
Traceback (most recent call last):
File "/usr/local/bin/psptool", line 33, in <module>
sys.exit(load_entry_point('psptool==2.2', 'console_scripts', 'psptool')())
File "/home/adrian/.local/lib/python3.9/site-packages/psptool/__main__.py", line 80, in main
psp = PSPTool.from_file(args.file, verbose=args.verbose)
File "/home/adrian/.local/lib/python3.9/site-packages/psptool/psptool.py", line 31, in from_file
pt = PSPTool(rom_bytes, verbose=verbose)
File "/home/adrian/.local/lib/python3.9/site-packages/psptool/psptool.py", line 39, in __init__
self.blob = Blob(rom_bytes, len(rom_bytes), self)
File "/home/adrian/.local/lib/python3.9/site-packages/psptool/blob.py", line 48, in __init__
self._find_entry_table()
File "/home/adrian/.local/lib/python3.9/site-packages/psptool/blob.py", line 87, in _find_entry_table
if self.dual_rom:
AttributeError: 'Blob' object has no attribute 'dual_rom'
```
is anything know? or just incompatible with 3.9?
Thanks a lot for your great work!

**Comment by cwerling** [comment]
Hi Adrian, thanks for your bug report. Nice catch! 

This was just a normal bug, didn't have anything to do with Python 3.9.

Happy new year! :)
